version: 2
updates:

  # Group Critical Security Updates
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/Los_Angeles"
    target-branch: "main"
    commit-message:
      prefix: "[golang-version]"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 0
    reviewers:
      - "Layr-Labs/eigenda-intg"
    labels:
      - "version"
      - "golang"
    allow:
      - dependency-type: "direct"
    groups:
      golang-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
