package server

import (
	"bytes"
	"fmt"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/Layr-Labs/eigenda-proxy/commitments"
	"github.com/Layr-Labs/eigenda-proxy/metrics"
	"github.com/Layr-Labs/eigenda-proxy/mocks"
	"github.com/ethereum/go-ethereum/log"
	"github.com/golang/mock/gomock"
	"github.com/gorilla/mux"
	"github.com/stretchr/testify/require"
)

const (
	simpleCommitmentPrefix = "\x00"

	// [alt-da, da layer, cert version]
	opGenericPrefixStr = "\x01\x00\x00"

	testCommitStr = "9a7d4f1c3e5b8a09d1c0fa4b3f8e1d7c6b29f1e6d8c4a7b3c2d4e5f6a7b8c9d0"
)

// TestRouting tests that the routes were properly encoded.
// We should eventually replace this with autogenerated specmatic tests over an openapi spec.
func TestRouting(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()
	mockRouter := mocks.NewMockIRouter(ctrl)

	m := metrics.NewMetrics("default")
	server := NewServer("localhost", 8080, mockRouter, log.New(), m)
	err := server.Start()
	require.NoError(t, err)

	tests := []struct {
		name         string
		url          string
		method       string
		mockBehavior func()
		expectedCode int
		expectedBody string
	}{
		{
			name:         "Not Found - Must have a commitment key",
			url:          "/get/0x",
			method:       http.MethodGet,
			mockBehavior: func() {},
			// originally we returned 400 for these, but now we return 404 because
			// not having a commitment is not a valid route.
			expectedCode: http.StatusNotFound,
			expectedBody: "404 page not found\n",
		},
		{
			name:         "Failure - Op Mode InvalidCommitmentKey",
			url:          "/get/0x1",
			mockBehavior: func() {},
			// originally we returned 400 for these, but now we return 404 because
			// not having a commitment is not a valid route.
			expectedCode: http.StatusNotFound,
			expectedBody: "404 page not found\n",
		},
		{
			name:         "Failure - Op Mode InvalidCommitmentKey",
			url:          "/get/0x999",
			mockBehavior: func() {},
			// originally we returned 400 for these, but now we return 404 because
			// not having a commitment is not a valid route.
			expectedCode: http.StatusNotFound,
			expectedBody: "404 page not found\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.mockBehavior()

			req := httptest.NewRequest(tt.method, tt.url, nil)
			rec := httptest.NewRecorder()
			server.httpServer.Handler.ServeHTTP(rec, req)

			require.Equal(t, tt.expectedCode, rec.Code)
			require.Equal(t, tt.expectedBody, rec.Body.String())

		})
	}
}

func TestHandleOPCommitments(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockRouter := mocks.NewMockIRouter(ctrl)

	m := metrics.NewMetrics("default")
	server := NewServer("localhost", 8080, mockRouter, log.New(), m)

	tests := []struct {
		name         string
		url          string
		mockBehavior func()
		expectedCode int
		expectedBody string
	}{
		{
			name: "Failure - OP Keccak256 Internal Server Error",
			url:  fmt.Sprintf("/get/0x00%s", testCommitStr),
			mockBehavior: func() {
				mockRouter.EXPECT().Get(gomock.Any(), gomock.Any(), gomock.Any()).Return(nil, fmt.Errorf("internal error"))
			},
			expectedCode: http.StatusInternalServerError,
			expectedBody: "",
		},
		{
			name: "Success - OP Keccak256",
			url:  fmt.Sprintf("/get/0x00%s", testCommitStr),
			mockBehavior: func() {
				mockRouter.EXPECT().Get(gomock.Any(), gomock.Any(), gomock.Any()).Return([]byte(testCommitStr), nil)
			},
			expectedCode: http.StatusOK,
			expectedBody: testCommitStr,
		},
		{
			name: "Failure - OP Alt-DA Internal Server Error",
			url:  fmt.Sprintf("/get/0x010000%s", testCommitStr),
			mockBehavior: func() {
				mockRouter.EXPECT().Get(gomock.Any(), gomock.Any(), gomock.Any()).Return(nil, fmt.Errorf("internal error"))
			},
			expectedCode: http.StatusInternalServerError,
			expectedBody: "",
		},
		{
			name: "Success - OP Alt-DA",
			url:  fmt.Sprintf("/get/0x010000%s", testCommitStr),
			mockBehavior: func() {
				mockRouter.EXPECT().Get(gomock.Any(), gomock.Any(), gomock.Any()).Return([]byte(testCommitStr), nil)
			},
			expectedCode: http.StatusOK,
			expectedBody: testCommitStr,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.mockBehavior()

			req := httptest.NewRequest(http.MethodGet, tt.url, nil)
			rec := httptest.NewRecorder()

			// To add the vars to the context,
			// we need to create a router through which we can pass the request.
			r := mux.NewRouter()
			server.registerRoutes(r)
			r.ServeHTTP(rec, req)

			require.Equal(t, tt.expectedCode, rec.Code)
			// We don't test for bodies because it's a specific error message
			// that contains a lot of information
			// require.Equal(t, tt.expectedBody, rec.Body.String())

		})
	}
}

func TestHandlerPut(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockRouter := mocks.NewMockIRouter(ctrl)
	server := NewServer("localhost", 8080, mockRouter, log.New(), metrics.NoopMetrics)

	tests := []struct {
		name                   string
		url                    string
		body                   []byte
		mockBehavior           func()
		expectedCode           int
		expectedBody           string
		expectError            bool
		expectedCommitmentMeta commitments.CommitmentMeta
	}{
		{
			name: "Failure OP Keccak256 - TooShortCommitmentKey",
			url:  "/put/0x",
			body: []byte("some data"),
			mockBehavior: func() {
				// Error is triggered before calling the router
			},
			expectedCode:           http.StatusBadRequest,
			expectedBody:           "",
			expectError:            true,
			expectedCommitmentMeta: commitments.CommitmentMeta{},
		},
		{
			name: "Failure OP Keccak256 - TooShortCommitmentKey",
			url:  "/put/0x1",
			body: []byte("some data"),
			mockBehavior: func() {
				// Error is triggered before calling the router
			},
			expectedCode:           http.StatusBadRequest,
			expectedBody:           "",
			expectError:            true,
			expectedCommitmentMeta: commitments.CommitmentMeta{},
		},
		{
			name: "Failure OP Keccak256 - InvalidCommitmentPrefixBytes",
			url:  fmt.Sprintf("/put/0x999%s", testCommitStr),
			body: []byte("some data"),
			mockBehavior: func() {
				// Error is triggered before calling the router
			},
			expectedCode:           http.StatusBadRequest,
			expectedBody:           "",
			expectError:            true,
			expectedCommitmentMeta: commitments.CommitmentMeta{},
		},
		{
			name: "Failure OP Mode Alt-DA - InternalServerError",
			url:  "/put",
			body: []byte("some data that will trigger an internal error"),
			mockBehavior: func() {
				mockRouter.EXPECT().Put(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).Return(nil, fmt.Errorf("internal error"))
			},
			expectedCode:           http.StatusInternalServerError,
			expectedBody:           "",
			expectError:            true,
			expectedCommitmentMeta: commitments.CommitmentMeta{},
		},
		{
			name: "Success OP Mode Alt-DA",
			url:  "/put",
			body: []byte("some data that will successfully be written to EigenDA"),
			mockBehavior: func() {
				mockRouter.EXPECT().Put(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).Return([]byte(testCommitStr), nil)
			},
			expectedCode:           http.StatusOK,
			expectedBody:           opGenericPrefixStr + testCommitStr,
			expectError:            false,
			expectedCommitmentMeta: commitments.CommitmentMeta{Mode: commitments.OptimismGeneric, CertVersion: 0},
		},
		{
			name: "Success OP Mode Keccak256",
			url:  fmt.Sprintf("/put/0x00%s", testCommitStr),
			body: []byte("some data that will successfully be written to EigenDA"),
			mockBehavior: func() {
				mockRouter.EXPECT().Put(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).Return([]byte(testCommitStr), nil)
			},
			expectedCode:           http.StatusOK,
			expectedBody:           "",
			expectError:            false,
			expectedCommitmentMeta: commitments.CommitmentMeta{Mode: commitments.OptimismKeccak, CertVersion: 0},
		},
		{
			name: "Success Simple Commitment Mode",
			url:  "/put?commitment_mode=simple",
			body: []byte("some data that will successfully be written to EigenDA"),
			mockBehavior: func() {
				mockRouter.EXPECT().Put(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).Return([]byte(testCommitStr), nil)
			},
			expectedCode:           http.StatusOK,
			expectedBody:           simpleCommitmentPrefix + testCommitStr,
			expectError:            false,
			expectedCommitmentMeta: commitments.CommitmentMeta{Mode: commitments.SimpleCommitmentMode, CertVersion: 0},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.mockBehavior()

			req := httptest.NewRequest(http.MethodPut, tt.url, bytes.NewReader(tt.body))
			rec := httptest.NewRecorder()

			meta, err := server.handlePut(rec, req)
			if tt.expectError {
				require.Error(t, err)
			} else {
				require.NoError(t, err)
			}
			require.Equal(t, tt.expectedCode, rec.Code)
			if !tt.expectError && tt.expectedBody != "" {
				require.Equal(t, []byte(tt.expectedBody), rec.Body.Bytes())
			}

			if !tt.expectError && tt.expectedBody == "" {
				require.Equal(t, []byte(nil), rec.Body.Bytes())
			}
			require.Equal(t, tt.expectedCommitmentMeta, meta)
		})
	}

	// for _, tt := range tests {
	// 	t.Run(tt.name+"/CheckMiddlewaresNoPanic", func(_ *testing.T) {
	// 		tt.mockBehavior()

	// 		req := httptest.NewRequest(http.MethodGet, tt.url, nil)
	// 		rec := httptest.NewRecorder()
	// 		// we also run the request through the middlewares, to make sure no panic occurs
	// 		// could happen if there's a problem with the metrics. For eg, in the past we saw
	// 		// panic: inconsistent label cardinality: expected 3 label values but got 1 in []string{"GET"}
	// 		handler := withLogging(withMetrics(server.handlePut, server.m, commitments.OptimismKeccak), server.log)
	// 		handler(rec, req)
	// 	})
	// }
}
