name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Build App
      run: make eigenda-proxy

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build container
        uses: docker/build-push-action@v5
        with:
          push: false
          context: .
          tags: eigenda-proxy

      - name: Run container as background process
        shell: bash
        run: |
          docker run -d \
          -p 6666:6666 \
          -e EIGENDA_PROXY_ADDR=0.0.0.0 \
          -e EIGENDA_PROXY_PORT=6666 \
          -e EIGENDA_PROXY_MEMSTORE_ENABLED=true \
          -e EIGENDA_PROXY_EIGENDA_CERT_VERIFICATION_DISABLED=true \
          eigenda-proxy

      - name: Wait for rpc to come up
        shell: bash
        run: |
          ${{ github.workspace }}/scripts/wait-for.sh