name: holesky-test

on:
  push:
    branches: [ "main" ]
  # pull_request_target is needed so that external contributors that create PRs from a forked repo
  # have access to the secrets needed to run the tests. There are security implications to this,
  # see https://stackoverflow.com/questions/74957218/what-is-the-difference-between-pull-request-and-pull-request-target-event-in-git
  # MAKE SURE TO ONLY ALLOW RUNNING THIS WORKFLOW AFTER REVIEWING THE PR!
  pull_request_target:
    branches: [ "main" ]

jobs:
  holesky-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Install project dependencies
      run: | 
        go mod download
    - name: Run holesky tests
      env: 
        SIGNER_PRIVATE_KEY:  ${{ secrets.SIGNER_PRIVATE_KEY }}
        ETHEREUM_RPC: ${{ secrets.ETHEREUM_RPC }}
      run: | 
        SIGNER_PRIVATE_KEY=$SIGNER_PRIVATE_KEY ETHEREUM_RPC=$ETHEREUM_RPC make holesky-test